name: Publish to NPM

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  tag:
    name: Add/update 'latest' tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js for NPM ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory
          rm -rf src
          echo Proceed to publishing on NPM
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js for GPR ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@waptik"

      - run: |
          echo Install dependencies
          npm ci
          echo Build source
          npm run build --if-present
          echo Delete source directory
          rm -rf src
          echo Proceed to publishing on GPR
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}